name: ferry_serializers
version: 0.0.0
homepage: https://ferrygraphql.com/
description: Serializers for conversion between GraphQL and Dart types
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  built_value: ^8.0.4
  ferry: ^0.10.3
dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
