name: ferry

packages:
  - examples/**
  - ferry/*
  - ferry_cache/*
  - ferry_exec/*
  - ferry_flutter/*
  - ferry_generator/*
  - ferry_hive_store/*
  - ferry_serializers/*
  - ferry_store/*
  - ferry_test_graphql/*
  - normalize/*
