name: ferry_sqlite_store
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ferry_store: ^0.6.1
  sqlite3: ^2.7.3
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
