targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: ferry_test_graphql|lib/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: ferry_test_graphql|lib/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
          custom_serializers:
            - import: 'package:ferry_test_graphql/date_serializer.dart'
              name: DateSerializer
