targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: ferry_test_graphql2|lib/schema/schema.graphql


      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: ferry_test_graphql2|lib/schema/schema.graphql


