name: ferry_test_graphql2
version: 0.2.4-dev.0
description: Example GraphQL Operations, used in Ferry tests
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async: ^2.0.0
  gql: '>=0.14.0 <2.0.0'
  gql_exec: '>=0.4.0 <2.0.0'
  gql_link: '>=0.5.0 <2.0.0'
  ferry_exec: ^0.3.1
  built_value: ^8.0.4
  built_collection: ^5.0.0
  gql_code_builder:
    git:
      url: https://github.com/fersonality/flutter_gql.git
      path: codegen/gql_code_builder
  ferry:
  ferry_cache:
dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.2
  pedantic: ^1.11.0
  built_value_generator: ^8.1.1
  dart_style: ^2.3.2
  ferry_generator:

dependency_overrides:
  gql_code_builder:
    git:
      url: https://github.com/fersonality/flutter_gql.git
      path: codegen/gql_code_builder
