targets:
  $default:
    sources:
      - lib/**
builders:
  graphql_builder:
    import: 'package:ferry_generator/graphql_builder.dart'
    builder_factories: ['graphqlBuilder']
    build_extensions:
      {
        '{{inputDir}}/{{file}}.graphql':
          [
            '{{dir}}/__generated__/{{file}}.ast.gql.dart',
            '{{dir}}/__generated__/{{file}}.data.gql.dart',
            '{{dir}}/__generated__/{{file}}.var.gql.dart',
            '{{dir}}/__generated__/{{file}}.req.gql.dart',
            '{{dir}}/__generated__/{{file}}.schema.gql.dart',
          ],
      }
    auto_apply: none
    build_to: source
    applies_builders:
      [
        'ferry_generator|serializer_builder',
        'built_value_generator|built_value',
      ]
    runs_before:
      [
        'ferry_generator|serializer_builder',
        'built_value_generator|built_value',
      ]

  serializer_builder:
    import: 'package:ferry_generator/serializer_builder.dart'
    builder_factories: ['serializerBuilder']
    build_extensions:
      {
        '{{dir}}/{{file}}.graphql':
          ['{{dir}}/__generated__/{{file}}.serializer.gql.dart'],
      }
    auto_apply: none
    build_to: source
    applies_builders: ['built_value_generator|built_value']
    runs_before: ['built_value_generator|built_value']
