name: test_graphql
version: 1.0.0
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  built_value: ^7.1.0
dev_dependencies: 
  build_runner: ^1.10.0
  gql_pedantic: ^1.0.2
  gql_build: ^0.1.0
  gql_code_builder: ^0.1.0
  ferry_generator: ^0.1.0
